//Activities
import {
  Armchair,
  Baby,
  Bathtub,
  Boat,
  Campfire,
  Car,
  Code,
  Crosshair,
  Detective,
  Envelope,
  Exam,
  File,
  FileCss,
  FileHtml,
  FileJs,
  FileJsx,
  FileTs,
  FileTsx,
  FilmScript,
  FilmStrip,
  FirstAidKit,
  GameController,
  Gear,
  GraduationCap,
  Headphones,
  House,
  Laptop,
  Lifebuoy,
  MapPin,
  Megaphone,
  Microphone,
  Newspaper,
  Package,
  PaintBrushHousehold,
  Phone,
  PhoneCall,
  Planet,
  ShoppingCart,
  Shower,
  Strategy,
  Target,
  Tree,
  UsersThree,
  VideoCamera,
} from "phosphor-react-native";
//Health
import {
  Baseball,
  Basketball,
  Bicycle,
  Football,
  ForkKnife,
  Heart,
  Horse,
  Medal,
  Mountains,
  SoccerBall,
  TennisBall,
  Trophy,
  Volleyball,
  YinYang,
} from "phosphor-react-native";
//Food
import {
  AppleLogo,
  BeerBottle,
  Brandy,
  Coffee,
  Cookie,
  CookingPot,
  Egg,
  Fish,
  Hamburger,
  Martini,
  Pizza,
  Popcorn,
  Wine,
} from "phosphor-react-native";
//General
import {
  Alarm,
  Alien,
  At,
  Binoculars,
  CheckSquare,
  Database,
  Ear,
  FacebookLogo,
  FaceMask,
  FileSearch,
  Globe,
  GlobeHemisphereEast,
  GlobeHemisphereWest,
  GlobeSimple,
  InstagramLogo,
  Lightbulb,
  MathOperations,
  Rainbow,
  Rocket,
  RocketLaunch,
  Smiley,
  SmileyNervous,
  SmileySad,
  SmileyWink,
  TiktokLogo,
  Translate,
  TwitterLogo,
  WhatsappLogo,
  YoutubeLogo,
} from "phosphor-react-native";
//Financial
import {
  ChartLine,
  ChartLineUp,
  ChartPie,
  Coin,
  Coins,
  CoinVertical,
  CreditCard,
  CurrencyBtc,
  CurrencyCny,
  CurrencyDollar,
  CurrencyEth,
  CurrencyGbp,
  PresentationChart,
  Receipt,
  Vault,
} from "phosphor-react-native";

export const icons = [
  {
    group: "Activities",
    icons: [
      {
        key: "arm-chair",
        name: "Arm Chair",
        component: <Armchair />,
      },
      {
        key: "campfire",
        name: "Campfire",
        component: <Campfire />,
      },
      {
        key: "baby",
        name: "Baby",
        component: <Baby />,
      },
      {
        key: "bathtub",
        name: "Bathtub",
        component: <Bathtub />,
      },
      {
        key: "boat",
        name: "Boat",
        component: <Boat />,
      },
      {
        key: "car",
        name: "Car",
        component: <Car />,
      },
      {
        key: "code",
        name: "Code",
        component: <Code />,
      },
      {
        key: "crosshair",
        name: "Crosshair",
        component: <Crosshair />,
      },
      {
        key: "detective",
        name: "Detective",
        component: <Detective />,
      },
      {
        key: "envelope",
        name: "Envelope",
        component: <Envelope />,
      },
      {
        key: "exam",
        name: "Exam",
        component: <Exam />,
      },
      {
        key: "file",
        name: "File",
        component: <File />,
      },
      {
        key: "file-css",
        name: "File CSS",
        component: <FileCss />,
      },
      {
        key: "file-html",
        name: "File HTML",
        component: <FileHtml />,
      },
      {
        key: "file-js",
        name: "File JS",
        component: <FileJs />,
      },
      {
        key: "file-jsx",
        name: "File JSX",
        component: <FileJsx />,
      },
      {
        key: "file-ts",
        name: "File TS",
        component: <FileTs />,
      },
      {
        key: "file-tsx",
        name: "File TSX",
        component: <FileTsx />,
      },
      {
        key: "film-script",
        name: "Film Script",
        component: <FilmScript />,
      },
      {
        key: "film-strip",
        name: "Film Strip",
        component: <FilmStrip />,
      },
      {
        key: "first-aid-kit",
        name: "First Aid Kit",
        component: <FirstAidKit />,
      },
      {
        key: "game-controller",
        name: "Game Controller",
        component: <GameController />,
      },
      {
        key: "gear",
        name: "Gear",
        component: <Gear />,
      },
      {
        key: "graduation-cap",
        name: "Graduation Cap",
        component: <GraduationCap />,
      },
      {
        key: "headphones",
        name: "Headphones",
        component: <Headphones />,
      },
      {
        key: "house",
        name: "House",
        component: <House />,
      },
      {
        key: "laptop",
        name: "Laptop",
        component: <Laptop />,
      },
      {
        key: "lifebuoy",
        name: "Lifebuoy",
        component: <Lifebuoy />,
      },
      {
        key: "map-pin",
        name: "Map Pin",
        component: <MapPin />,
      },
      {
        key: "megaphone",
        name: "Megaphone",
        component: <Megaphone />,
      },
      {
        key: "microphone",
        name: "Microphone",
        component: <Microphone />,
      },
      {
        key: "newspaper",
        name: "Newspaper",
        component: <Newspaper />,
      },
      {
        key: "package",
        name: "Package",
        component: <Package />,
      },
      {
        key: "paint-brush-household",
        name: "Paint Brush Household",
        component: <PaintBrushHousehold />,
      },
      {
        key: "phone",
        name: "Phone",
        component: <Phone />,
      },
      {
        key: "phone-call",
        name: "Phone Call",
        component: <PhoneCall />,
      },
      {
        key: "planet",
        name: "Planet",
        component: <Planet />,
      },
      {
        key: "shopping-cart",
        name: "Shopping Cart",
        component: <ShoppingCart />,
      },
      {
        key: "shower",
        name: "Shower",
        component: <Shower />,
      },
      {
        key: "strategy",
        name: "Strategy",
        component: <Strategy />,
      },
      {
        key: "target",
        name: "Target",
        component: <Target />,
      },
      {
        key: "tree",
        name: "Tree",
        component: <Tree />,
      },
      {
        key: "users-three",
        name: "Users Three",
        component: <UsersThree />,
      },
      {
        key: "video-camera",
        name: "Video Camera",
        component: <VideoCamera />,
      },
    ],
  },
  {
    group: "Health",
    icons: [
      {
        key: "baseball",
        name: "Baseball",
        component: <Baseball />,
      },
      {
        key: "basketball",
        name: "Basketball",
        component: <Basketball />,
      },
      {
        key: "bicycle",
        name: "Bicycle",
        component: <Bicycle />,
      },
      {
        key: "football",
        name: "Football",
        component: <Football />,
      },
      {
        key: "fork-knife",
        name: "Fork Knife",
        component: <ForkKnife />,
      },
      {
        key: "heart",
        name: "Heart",
        component: <Heart />,
      },
      {
        key: "horse",
        name: "Horse",
        component: <Horse />,
      },
      {
        key: "medal",
        name: "Medal",
        component: <Medal />,
      },
      {
        key: "mountains",
        name: "Mountains",
        component: <Mountains />,
      },
      {
        key: "soccer-ball",
        name: "Soccer Ball",
        component: <SoccerBall />,
      },
      {
        key: "tennis-ball",
        name: "Tennis Ball",
        component: <TennisBall />,
      },
      {
        key: "trophy",
        name: "Trophy",
        component: <Trophy />,
      },
      {
        key: "volleyball",
        name: "Volleyball",
        component: <Volleyball />,
      },
      {
        key: "yin-yang",
        name: "Yin Yang",
        component: <YinYang />,
      },
    ],
  },
  {
    group: "Food",
    icons: [
      {
        key: "apple-logo",
        name: "Apple Logo",
        component: <AppleLogo />,
      },
      {
        key: "beer-bottle",
        name: "Beer Bottle",
        component: <BeerBottle />,
      },
      {
        key: "brandy",
        name: "Brandy",
        component: <Brandy />,
      },
      {
        key: "coffee",
        name: "Coffee",
        component: <Coffee />,
      },
      {
        key: "cookie",
        name: "Cookie",
        component: <Cookie />,
      },
      {
        key: "cooking-pot",
        name: "Cooking Pot",
        component: <CookingPot />,
      },
      {
        key: "egg",
        name: "Egg",
        component: <Egg />,
      },
      {
        key: "fish",
        name: "Fish",
        component: <Fish />,
      },
      {
        key: "hamburger",
        name: "Hamburger",
        component: <Hamburger />,
      },
      {
        key: "martini",
        name: "Martini",
        component: <Martini />,
      },
      {
        key: "pizza",
        name: "Pizza",
        component: <Pizza />,
      },
      {
        key: "popcorn",
        name: "Popcorn",
        component: <Popcorn />,
      },
      {
        key: "wine",
        name: "Wine",
        component: <Wine />,
      },
    ],
  },
  {
    group: "General",
    icons: [
      {
        key: "check-square",
        name: "Check Square",
        component: <CheckSquare />,
      },
      {
        key: "alarm",
        name: "Alarm",
        component: <Alarm />,
      },
      {
        key: "alien",
        name: "Alien",
        component: <Alien />,
      },
      {
        key: "at",
        name: "At",
        component: <At />,
      },
      {
        key: "binoculars",
        name: "Binoculars",
        component: <Binoculars />,
      },
      {
        key: "database",
        name: "Database",
        component: <Database />,
      },
      {
        key: "ear",
        name: "Ear",
        component: <Ear />,
      },
      {
        key: "facebook-logo",
        name: "Facebook Logo",
        component: <FacebookLogo />,
      },
      {
        key: "face-mask",
        name: "Face Mask",
        component: <FaceMask />,
      },
      {
        key: "file-search",
        name: "File Search",
        component: <FileSearch />,
      },
      {
        key: "globe",
        name: "Globe",
        component: <Globe />,
      },
      {
        key: "globe-hemisphere-east",
        name: "Globe Hemisphere East",
        component: <GlobeHemisphereEast />,
      },
      {
        key: "globe-hemisphere-west",
        name: "Globe Hemisphere West",
        component: <GlobeHemisphereWest />,
      },
      {
        key: "globe-simple",
        name: "Globe Simple",
        component: <GlobeSimple />,
      },
      {
        key: "instagram-logo",
        name: "Instagram Logo",
        component: <InstagramLogo />,
      },
      {
        key: "math-operations",
        name: "Math Operations",
        component: <MathOperations />,
      },
      {
        key: "rainbow",
        name: "Rainbow",
        component: <Rainbow />,
      },
      {
        key: "rocket",
        name: "Rocket",
        component: <Rocket />,
      },
      {
        key: "rocket-launch",
        name: "Rocket Launch",
        component: <RocketLaunch />,
      },
      {
        key: "smiley",
        name: "Smiley",
        component: <Smiley />,
      },
      {
        key: "smiley-nervous",
        name: "Smiley Nervous",
        component: <SmileyNervous />,
      },
      {
        key: "smiley-sad",
        name: "Smiley Sad",
        component: <SmileySad />,
      },
      {
        key: "smiley-wink",
        name: "Smiley Wink",
        component: <SmileyWink />,
      },
      {
        key: "tiktok-logo",
        name: "Tiktok Logo",
        component: <TiktokLogo />,
      },
      {
        key: "translate",
        name: "Translate",
        component: <Translate />,
      },
      {
        key: "twitter-logo",
        name: "Twitter Logo",
        component: <TwitterLogo />,
      },
      {
        key: "whatsapp-logo",
        name: "Whatsapp Logo",
        component: <WhatsappLogo />,
      },
      {
        key: "youtube-logo",
        name: "Youtube Logo",
        component: <YoutubeLogo />,
      },
      {
        key: "lightbulb",
        name: "Lightbulb",
        component: <Lightbulb />,
      },
    ],
  },
  {
    group: "Financial",
    icons: [
      {
        key: "chart-line",
        name: "Chart Line",
        component: <ChartLine />,
      },
      {
        key: "chart-line-up",
        name: "Chart Line Up",
        component: <ChartLineUp />,
      },
      {
        key: "chart-pie",
        name: "Chart Pie",
        component: <ChartPie />,
      },
      {
        key: "coin",
        name: "Coin",
        component: <Coin />,
      },
      {
        key: "coins",
        name: "Coins",
        component: <Coins />,
      },
      {
        key: "coin-vertical",
        name: "Coin Vertical",
        component: <CoinVertical />,
      },
      {
        key: "credit-card",
        name: "Credit Card",
        component: <CreditCard />,
      },
      {
        key: "currency-btc",
        name: "Currency BTC",
        component: <CurrencyBtc />,
      },
      {
        key: "currency-cny",
        name: "Currency CNY",
        component: <CurrencyCny />,
      },
      {
        key: "currency-dollar",
        name: "Currency Dollar",
        component: <CurrencyDollar />,
      },
      {
        key: "currency-eth",
        name: "Currency ETH",
        component: <CurrencyEth />,
      },
      {
        key: "currency-gbp",
        name: "Currency GBP",
        component: <CurrencyGbp />,
      },
      {
        key: "presentation-chart",
        name: "Presentation Chart",
        component: <PresentationChart />,
      },
      {
        key: "receipt",
        name: "Receipt",
        component: <Receipt />,
      },
      {
        key: "vault",
        name: "Vault",
        component: <Vault />,
      },
    ],
  },
];
